### ISSUE TITLE
Example 1 - buttons(increase/decrease) are not styled

### ISSUE THREAD

**Issue by gangash004** [sonusindhu/angular-signals-examples#3]
Hi,
just noticed the button style not looks good for the increase/decrease. 
![image](https://user-images.githubusercontent.com/33139633/236607956-cc85efbf-8e6a-4e8c-a6ea-3ba9d322f562.png)

**Comment by sonusindhu** [comment]
style is not yet implemented, if anyone can pick then most welcome
thanks

**Comment by Vaibhav-28** [comment]
I have raised a [PR](https://github.com/sonusindhu/angular-signals-examples/pull/4) for this issue

**Comment by sonusindhu** [comment]
fixed with #6
